/** Aligned to `docs/LOADS_DATA_MAP.md` — container_number on `containers`, not `loads`. */
export const LOAD_LIST_SELECT = `
  id,
  reference_number,
  status,
  pickup_location,
  delivery_location,
  return_location,
  pickup_apt_from,
  pickup_apt_to,
  delivery_apt_from,
  delivery_apt_to,
  is_hot,
  notes,
  freight_hold,
  customs_hold,
  terminal_hold,
  fees_hold,
  other_hold,
  carrier_hold,
  created_at,
  containers ( container_number ),
  customers ( name )
`;

/** Detail master data — see `docs/LOADS_DATA_MAP.md` §2.2. */
export const LOAD_DETAIL_SELECT = `
  id,
  reference_number,
  status,
  pickup_location,
  delivery_location,
  return_location,
  pickup_apt_from,
  pickup_apt_to,
  delivery_apt_from,
  delivery_apt_to,
  is_hot,
  notes,
  load_type,
  route_type,
  ssl,
  mbol,
  house_bol,
  seal_number,
  chassis_number,
  container_size,
  scheduled_pickup,
  actual_pickup,
  actual_delivery,
  completed_date,
  created_at,
  is_hazmat,
  is_overweight,
  is_bonded,
  freight_hold,
  customs_hold,
  terminal_hold,
  fees_hold,
  other_hold,
  carrier_hold,
  containers (
    container_number,
    bol_number,
    size,
    type,
    seal_number
  ),
  customers (
    name,
    phone,
    address,
    city,
    state,
    zip_code
  ),
  drivers ( name, phone )
`;
