/** User-facing copy (English). */
export const strings = {
  app: {
    /** Display name on login, drawer, and device home screen (via app.json). */
    name: 'Tigerhawk Mobile',
    tagline: 'Houston Drayage',
  },
  auth: {
    signIn: 'Sign in',
    email: 'Email',
    username: 'Username',
    usernameOrEmail: 'Username or email',
    password: 'Password',
    signInButton: 'Sign in',
    signingIn: 'Signing in…',
    signOut: 'Sign out',
    sessionActive: 'Session active',
    sessionNone: 'No session',
    sessionReady: 'Ready (no session)',
    supabaseLabel: 'Supabase',
    signInFailed: 'Could not sign in. Check your username/email and password.',
    invalidCredentials: 'Incorrect username or password.',
    callbackSigningIn: 'Completing sign-in…',
    callbackFailed: 'Sign-in link failed or expired.',
    callbackInvalid: 'Invalid sign-in redirect.',
    magicLinkSent: 'Check your email for the sign-in link.',
    sendMagicLink: 'Email me a sign-in link',
    contactDispatchPassword:
      'Forgot your password? Contact dispatch — they can resend your setup link.',
    usernameApiNotDeployed:
      'Username login is not available on this TMS host. Contact dispatch or try again later.',
    usernameOrEmailHint: 'Sign in with your driver username. Email is a backup only.',
    driverSubtitle: 'Driver app',
    devMockHint: 'Dev demo (mock only):',
    notDriverRole:
      'This account is not a mobile driver. Ask dispatch to enable Tigerhawk Mobile for your username.',
  },
  network: {
    offlineTitle: 'No internet connection',
    offlineMessage:
      'You can still view cached screens. Pull to refresh or try again when you are back online.',
    offlineFetchBlocked:
      'No internet connection. Connect to load or update data.',
    offlineActionBlocked:
      'This action needs internet. Reconnect and try again.',
    offlineUploadBlocked:
      'Photo upload needs internet. Reconnect and try again.',
    offlineUploadQueued:
      'Photo saved. It will upload when you are back online.',
    offlineStatusQueued:
      'Status saved. It will sync when you are back online.',
    offlineQueueBanner: (count: number) =>
      count === 1
        ? '1 action waiting to sync when online'
        : `${count} actions waiting to sync when online`,
    offlineQueueBannerA11y: (count: number) =>
      `${count} pending offline action${count === 1 ? '' : 's'}`,
  },
  location: {
    sectionTitle: 'Your location',
    disclaimer:
      'Location is used only while this app is open to help dispatch see where you are on an assigned load. Tigerhawk Mobile does not track your location in the background.',
    permissionWhenInUseTitle: 'Location access',
    permissionWhenInUseMessage:
      'Tigerhawk Mobile needs your location while the app is open so you can share your position with dispatch for assigned loads.',
    permissionDeniedTitle: 'Location unavailable',
    permissionDeniedMessage:
      'Location was denied. You can enable it in device Settings, or contact dispatch by phone.',
    openSettings: 'Open Settings',
    notAvailableOnWeb: 'Location sharing is available on the mobile app only.',
    loading: 'Getting location…',
    shareLocation: 'Share location',
    shareLocationA11y: 'Share load, driver, and GPS details with dispatch',
    coordinatesLabel: 'Coordinates',
    accuracyLabel: 'Accuracy',
    lastUpdatedLabel: 'Updated',
    shareFailed: 'Could not read location. Try again outdoors with GPS enabled.',
    servicesDisabledMessage:
      'Turn on Location Services in your device settings, then try again.',
    lowPowerHint:
      'Battery saver is on — GPS may take longer or show lower accuracy. Move outdoors if needed.',
    shareDialogTitle: 'Share load location',
    shareMessageLoadLabel: 'Load',
    shareMessageStatusLabel: 'Status',
    shareMessageContainerLabel: 'Container',
    shareMessageRouteLabel: 'Route',
    shareMessageDriverLabel: 'Driver',
    shareMessageDriverPhoneLabel: 'Driver phone',
    shareMessageDriverEmailLabel: 'Driver email',
    shareMessageMapsLabel: 'Open in Maps',
    shareMessageFooter: 'Shared via Tigerhawk Mobile',
    openInMaps: 'Open in Maps',
    mapsLinkA11y: 'Open coordinates in maps app',
    mapsOpenFailed: 'Could not open the maps app. Please try again.',
    tmsShareOnlyHint:
      'Live tracking updates dispatch while this load detail is open. Share location below sends coordinates manually (WhatsApp, etc.).',
    liveTrackingBanner: 'Sharing location with dispatch',
    liveTrackingLastSent: (label: string) => `Last sent: ${label}`,
    liveTrackingSending: 'Sending first location update…',
    liveTrackingPausedOffline: 'Location sharing paused — waiting for connection.',
    liveTrackingSettingsTitle: 'Location needed for dispatch',
    liveTrackingSettingsHint:
      'Turn on location access so dispatch can see your position on this load.',
    liveTrackingBannerA11y: 'Live location sharing with dispatch is active',
    liveTrackingServerBlocked:
      'Location could not be saved. Ask dispatch to apply the PP2 GPS database fix in Supabase.',
  },
  tabs: {
    loads: 'Loads',
    clock: 'Clock',
    account: 'Account',
  },
  nav: {
    loads: 'My Loads',
    clock: 'Clock',
    history: 'Load History',
    account: 'Account',
    logOut: 'Log Out',
    brandTitle: 'Tigerhawk Mobile',
    brandSubtitle: 'Houston Drayage',
  },
  clock: {
    title: 'Clock',
    loading: 'Loading clock status…',
    clockIn: 'Clock In',
    clockOut: 'Clock Out',
    clockInA11y: 'Clock in for duty',
    clockOutA11y: 'Clock out — you remain assigned to your loads',
    toastIn: "You've clocked in!",
    toastOut: "You've clocked out!",
    /** Q11 — shown after successful clock out (I.3). */
    toastOutOffDuty:
      "You're off duty. Your loads stay assigned to you.",
    statusOnDuty: 'On duty',
    statusOffDuty: 'Off duty',
    emptyHistory: 'You have not recorded any time today.',
    workingLabel: 'Working',
    sessionStarted: 'Started',
    timerA11y: 'Elapsed time on duty',
    dateA11y: 'Today in Central Time',
    centralHint: 'Times shown in America/Chicago (Central).',
    retry: 'Try again',
    notDriver:
      'Clock is available for assigned drivers only. Contact dispatch if this is wrong.',
  },
  loads: {
    title: 'My loads',
    subtitle: 'Active and upcoming moves',
    tabActive: 'Active',
    tabUpcoming: 'Upcoming',
    activeEmptyTitle: 'No active moves',
    activeEmptyMessage:
      'When you start a move, it shows up here. Pull to refresh anytime.',
    upcomingEmptyTitle: 'No upcoming moves',
    upcomingEmptyMessage:
      'Assigned moves you have not started yet appear here — accepted or waiting.',
    fromSupabase: 'Data from Supabase (driver RLS)',
    fromMock: 'Mock data (client demo)',
    noData: 'No data',
    emptyTitle: 'No assigned loads',
    emptyMessage: 'There are no loads for this driver. Pull to refresh.',
    loading: 'Loading your moves…',
    loadingMore: 'Loading more…',
    retry: 'Try again',
    scrollForMore: 'Scroll for more loads',
    endOfList: 'All loads loaded',
    showingCount: (shown: number, total: number) =>
      `Showing ${shown} of ${total} loads`,
    showingMany: (shown: number) => `${shown} load(s) loaded`,
    showLoads: 'Show loads',
    emptyDemo: 'Empty demo',
    demoError: 'Demo error',
    clearError: 'Clear error',
    refreshFailed: 'Could not refresh loads.',
    container: 'Container',
    loadType: 'Load type',
    nextAction: 'Next',
    acceptedAt: 'Accepted',
    startedAt: 'Started',
    noLocationContactDispatch: 'No location — contact dispatch',
    flagHot: 'HOT',
    flagHazmat: 'HAZMAT',
    moveCardA11y: 'Move card',
    delivery: 'Delivery',
    activeHold: 'Active hold — contact dispatch',
  },
  moveOffer: {
    reject: 'Reject',
    accept: 'Accept Move',
    rejectA11y: 'Reject assigned move',
    acceptA11y: 'Choose how to accept assigned move',
    acceptSheetTitle: 'Accept Move',
    acceptSheetMessage: (moveLabel: string) =>
      `Choose when to start move ${moveLabel}.`,
    acceptAndStart: 'Accept & Start Move',
    acceptStartLater: 'Accept, Start Later',
    cancelAccept: 'Cancel',
    fallbackMoveLabel: 'assigned move',
    rejectSheetTitle: 'Reject Move',
    rejectSheetMessage: (moveLabel: string) =>
      `Reject move ${moveLabel} and return it to dispatch.`,
    rejectReasonLabel: 'Reason (optional)',
    rejectReasonPlaceholder: 'Tell dispatch why you cannot take this move',
    rejectReasonA11y: 'Reason for rejecting move',
    confirmReject: 'Reject Move',
    cancelReject: 'Cancel',
    startMove: 'Start Move',
    startMoveA11y: 'Start accepted move',
    acceptedToast: 'You have accepted this move.',
    startedToast: 'Move started.',
    dismissError: 'Dismiss',
  },
  driverProgress: {
    title: 'Move progress',
    loading: 'Loading move progress…',
    startMove: 'Start Move',
    enroute: 'Enroute',
    arrived: 'Arrived',
    complete: 'Complete Load',
    completeA11y: 'Complete this load',
    alreadyCompleted: 'This load is complete.',
    confirmTitle: 'Confirm action',
    confirmMessage: (action: string, currentProgress: string) =>
      `${action} from “${currentProgress}”?`,
    confirm: 'Continue',
    cancel: 'Cancel',
    actionA11y: (action: string) => `${action} for this move`,
    started: 'Move started.',
    enrouteSaved: 'Departure saved.',
    arrivalSaved: 'Arrival saved.',
    completed: 'Load completed.',
    chassisPromptTitle: 'Chassis number required',
    chassisPromptMessage:
      'Enter the chassis number received at pickup, then retry Arrived.',
    requirementsTitle: 'Complete load requirements',
    requirementsMessage:
      'Provide every item in the checklist from the server. Do not skip listed gaps.',
    checklistTitle: 'Required to complete',
    checklistExactHint:
      'This list is exactly what the TMS returned — nothing is added on the phone.',
    chassisNumber: 'Chassis number',
    chassisPlaceholder: 'Enter chassis number',
    enterChassis: 'Enter chassis number',
    containerNumber: 'Container number',
    containerPlaceholder: 'Enter container number',
    sealNumber: 'Seal number',
    sealPlaceholder: 'Enter seal number',
    requiredField: 'This field is required.',
    saveAndContinue: 'Save and continue',
    provideMissingInfo: 'Provide missing info',
    addRequiredDocuments: 'Add required photos',
    missingChassis: 'Chassis number',
    missingContainer: 'Container number',
    missingSeal: 'Seal number',
    missingTirOut: 'TIR Out photo',
    missingTirIn: 'TIR In photo',
  },
  loadHistory: {
    title: 'Load History',
    searchPlaceholder: 'Search Loads…',
    searchA11y: 'Search load history',
    dateRangeTitle: 'Date range',
    dateRangeA11y: (label: string) => `Date range ${label}`,
    presetYesterdayToday: 'Yesterday – Today',
    presetLast7Days: 'Last 7 days',
    presetLast30Days: 'Last 30 days',
    cancelRange: 'Cancel',
    loading: 'Loading load history…',
    emptyTitle: 'Could not find load history in the date range',
    emptyMessage: (rangeLabel: string) => rangeLabel,
    reload: 'Reload',
    reloadA11y: 'Reload load history',
  },
  account: {
    title: 'Account',
    driverRole: 'Driver',
    roleLabel: 'Role',
    emailLabel: 'Email',
    loadingProfile: 'Loading profile…',
    noProfile: 'No office profile on file — that is normal for truck drivers.',
    usernameLabel: 'Username',
    devMockActive: 'Dev mock session is also active',
    sessionLabel: 'Session',
    lastEvent: 'Last event',
    errorLabel: 'Error',
    refreshSession: 'Refresh session',
    environment: 'Environment',
    projectLabel: 'Project',
  },
  loadDetail: {
    notFound: 'Load not found',
    loading: 'Loading load details…',
    readOnlyHint: 'Load information is read-only and comes from the TMS.',
    reference: 'Reference',
    route: 'Route',
    pickup: 'Pickup',
    delivery: 'Delivery',
    returnEmpty: 'Return',
    customer: 'Customer',
    customerPhone: 'Phone',
    customerAddress: 'Address',
    shipment: 'Shipment',
    loadType: 'Load type',
    routeType: 'Route type',
    ssl: 'SSL',
    mbol: 'MBOL',
    houseBol: 'House BOL',
    container: 'Container',
    containerSize: 'Size',
    containerType: 'Type',
    bolNumber: 'BOL',
    sealNumber: 'Seal',
    chassis: 'Chassis',
    timeline: 'Timeline',
    scheduledPickup: 'Scheduled pickup',
    actualPickup: 'Actual pickup',
    actualDelivery: 'Actual delivery',
    completed: 'Completed',
    flags: 'Load flags',
    hazmat: 'Hazmat',
    overweight: 'Overweight',
    bonded: 'Bonded',
    yes: 'Yes',
    no: 'No',
    holds: 'Active holds',
    holdsNote: 'Contact dispatch before changing status.',
    notes: 'Notes',
    messages: 'Messages',
    noMessages: 'No messages on this load.',
    pod: 'POD / Documents',
    documents: 'Documents',
    documentsBlockA11y: 'Required documents: TIR Out, proof of delivery signature, TIR In',
    documentsListA11y: 'Uploaded documents and driver evidence',
    documentsPortProHint:
      'Required for Complete: TIR Out photo, Proof of Delivery signature, and TIR In photo. Optional driver evidence is below the file list.',
    tirOutRow: 'TIR Out',
    tirInRow: 'TIR In',
    podSignRow: 'Proof of Delivery (Sign)',
    tirOutAdd: 'Add TIR Out photo',
    tirOutAddA11y: 'Add TIR Out photo from camera or gallery',
    tirInAdd: 'Add TIR In photo',
    tirInAddA11y: 'Add TIR In photo from camera or gallery',
    tirPickMessage: 'Choose camera or photo library for this required document.',
    docRowMissing: 'Missing',
    docRowUploaded: 'Uploaded',
    docRowUploadedWithName: (filename: string) => `Uploaded · ${filename}`,
    docRowPodCaptured: 'Signature captured',
    documentsNote:
      'BOL, rate confirmations, and other dispatch uploads appear here. Pull to refresh after any upload.',
    documentsLoading: 'Loading documents…',
    noDocuments: 'No documents on this load yet.',
    documentView: 'View',
    documentOpenFailed: 'Could not open document',
    documentLinkExpired:
      'This download link has expired. Pull down on this screen to refresh the list, then tap View again.',
    documentRemoved:
      'This file is no longer on the load. Pull down to refresh the document list.',
    documentUnavailable:
      'This file could not be opened. Pull down to refresh, or ask dispatch if the problem continues.',
    documentNoUrl:
      'This file has no download link yet. Pull to refresh or ask dispatch to re-upload.',
    documentOpening: 'Opening document…',
    driverEvidenceTitle: 'Driver evidence (optional)',
    driverEvidenceHint:
      'Add optional photos of interest. Legal proof of delivery is only Sign on device above. Photos are never the legal POD.',
    driverDocBadge: 'from mobile',
    podAddPhoto: 'Add photo',
    podAddPhotoA11y: 'Add driver evidence photo from camera or gallery',
    podSignOnDevice: 'Sign on device',
    podSignOnDeviceA11y: 'Open signature pad for the legal TMS-stamped POD',
    podPickTitle: 'Add photo',
    podPickMessage: 'Choose camera or photo library for driver evidence photos.',
    podPickCamera: 'Take photo',
    podPickGallery: 'Choose from gallery',
    podConfirmHint:
      'Check the photo is clear, then upload or cancel. Legal signatures use Sign on device above.',
    podUpload: 'Upload',
    podUploadA11y: 'Upload selected image to TMS',
    podCancel: 'Cancel',
    podCancelA11y: 'Cancel photo upload',
    podDiscardTitle: 'Discard image?',
    podDiscardMessage: 'The selected photo will not be uploaded.',
    podDiscardConfirm: 'Discard',
    podKeepEditing: 'Keep editing',
    podPreviewA11y: 'Preview of selected driver photo',
    podUploadSuccess:
      'Uploaded. It will appear in TMS Documents and in this list without reloading.',
    podLegalHint:
      'Proof of delivery is stamped by the TMS from this signature. The app does not generate a PDF.',
    podLoading: 'Loading POD preview…',
    podState: 'POD state',
    podStateUnsigned: 'Unsigned',
    podStatePending: 'Pending stamp',
    podStateSigned: 'Signed',
    podDeliveryAddress: 'Delivery address',
    podSignerName: 'Signer name',
    podSignerRequired: 'Enter who is signing before opening the pad.',
    podNoSkipHint: 'Signature is required to leave delivery. There is no Skip.',
    podSignatureSigned: 'Signature accepted. POD is stamped.',
    podSignaturePending:
      'Signature accepted. POD stamp is pending — you may continue.',
    podSignatureQueued:
      'Signature saved offline. It will upload before you leave delivery.',
    signatureTitle: 'Receipt signature',
    signatureHint:
      'Ask the receiver to sign below with a finger or stylus. This is the legal POD stamp — not a photo upload.',
    signatureLegalHint:
      'By signing, the receiver acknowledges receipt of the shipment in apparent good condition except as noted.',
    signatureClear: 'Clear',
    signatureClearA11y: 'Clear signature pad',
    signatureConfirm: 'Use signature',
    signatureConfirmA11y: 'Confirm signature and submit to TMS',
    signatureCancelA11y: 'Cancel signature capture',
    signaturePadA11y: 'White signature pad for finger or stylus',
    signatureEmptyError: 'Please provide a signature before confirming.',
    signatureExportError: 'Could not save the signature image. Try again.',
    signatureUploadSuccess: 'Signature submitted for TMS stamp.',
    signatureWebUnsupported:
      'On-device signature works on a phone or tablet build. Use Add photo on web, or open the native app.',
    driverUploadInvalidMime:
      'Only JPEG, PNG, HEIC, or WebP images can be uploaded (maximum 50 MB).',
    driverUploadFileTooLarge: 'This photo exceeds the 50 MB limit. Choose a smaller file.',
    driverUploadEmptyFile: 'This file is empty. Choose another photo.',
    podOfflineHint: 'Connect to the internet to upload a driver photo.',
    podOfflineQueueHint:
      'You are offline. Confirm upload to queue it — it will sync when you reconnect.',
    documentTypeLabel: 'Document type',
    documentTypeDriver: 'Driver evidence',
    documentTypeDriverHint: 'Delivery, seal, delay, or incident photos',
    documentTypePod: 'POD',
    documentTypePodHint:
      'Not used for legal POD — use Sign on device. Optional photos use Driver evidence.',
    documentTypePhoto: 'Photo',
    documentTypePhotoHint: 'Damage, delay, or other field incidents',
    mediaPermissionDeniedTitle: 'Camera or photos access needed',
    mediaPermissionDeniedMessage:
      'Allow camera or photo library access in Settings to add driver documents.',
    mediaPermissionOpenSettings: 'Open Settings',
    screenTitle: 'Load details',
    emDash: '—',
  },
  waitTime: {
    sectionTitle: 'Delivery wait & detention',
    phaseIdle: 'Not started',
    phaseFree: 'Free waiting time',
    phaseBillable: 'Billable detention',
    phaseStopped: 'Stopped',
    freeRemaining: (minutes: number) =>
      `${minutes} min free time remaining`,
    exceededBanner:
      'Detention billing may apply — dispatch has been notified. Billable time after 60 minutes free.',
    mockHint: 'Demo mode — timer stored locally (Phase A).',
    checkIn: 'Check In',
    checkInHint:
      'Tap when you are present for unloading at the customer. Required to start wait time and detention billing.',
    checkInA11y: 'Check in for delivery wait and detention billing',
    checkOut: 'Check Out',
    checkOutHint:
      'Ends the wait timer (service complete at customer). Load status stays the same unless you change it below.',
    checkOutA11y: 'Check out and stop delivery wait timer',
    /** @deprecated Use checkIn — kept for doc references */
    startWaitTime: 'Check In',
    startWaitTimeHint:
      'Tap when you are present for unloading at the customer. Required to start wait time and detention billing.',
    startWaitTimeA11y: 'Check in for delivery wait and detention billing',
    /** @deprecated Use checkOut */
    endWaitTime: 'Check Out',
    endWaitTimeHint:
      'Ends the wait timer (service complete at customer). Load status stays the same unless you change it below.',
    endWaitTimeA11y: 'Check out and stop delivery wait timer',
    syncHint: 'Syncing wait time with the server…',
    paySummaryTitle: 'Your wait pay',
    accruedTimeLabel: 'Accrued wait time',
    estimatedPayLabel: 'Estimated wait pay',
    payEstimateHint:
      'Estimate while the timer runs. Final pay is confirmed when the load is completed.',
    payReadOnlyHint: 'Read-only. Contact dispatch with questions about your pay.',
    paySummaryA11y: 'Read-only summary of accrued wait time and estimated pay',
  },
  driverActions: {
    title: 'Field actions',
    transitionDenied: 'Transition not allowed for driver.',
    noActions: 'Load is in a final state or has no field actions.',
    updated: 'Updated',
    sessionRequired: 'Session expired. Sign in again.',
    updateFailed: 'Failed to update status.',
    changeStatusA11y: 'Change status to',
    blockedByHoldsA11y: 'Blocked while holds are active',
  },
} as const;
