/** User-facing copy (English). */
export const strings = {
  auth: {
    signIn: 'Sign in',
    email: 'Email',
    password: 'Password',
    signInButton: 'Sign in',
    signingIn: 'Signing in…',
    signOut: 'Sign out',
    sessionActive: 'Session active',
    sessionNone: 'No session',
    sessionReady: 'Ready (no session)',
    supabaseLabel: 'Supabase',
    signInFailed: 'Could not sign in. Check your email and password.',
    invalidCredentials: 'Invalid email or password.',
    callbackSigningIn: 'Completing sign-in…',
    callbackFailed: 'Sign-in link failed or expired.',
    callbackInvalid: 'Invalid sign-in redirect.',
    magicLinkSent: 'Check your email for the sign-in link.',
    sendMagicLink: 'Email me a sign-in link',
    driverSubtitle: 'Driver · Houston Drayage',
    devMockHint: 'Dev demo (mock only):',
    notDriverRole: 'This account is not a driver. Use a driver profile to access loads.',
  },
  tabs: {
    loads: 'Loads',
    account: 'Account',
  },
  nav: {
    loads: 'My Loads',
    account: 'Account',
    logOut: 'Log Out',
    brandTitle: 'TigerHawk',
    brandSubtitle: 'Logistics',
  },
  loads: {
    title: 'My loads',
    fromSupabase: 'Data from Supabase (driver RLS)',
    fromMock: 'Mock data (client demo)',
    noData: 'No data',
    emptyTitle: 'No assigned loads',
    emptyMessage: 'There are no loads for this driver. Pull to refresh.',
    loading: 'Loading your loads…',
    loadingMore: 'Loading more…',
    retry: 'Try again',
    scrollForMore: 'Scroll for more loads',
    showingCount: (shown: number, total: number) =>
      `Showing ${shown} of ${total} loads`,
    showingMany: (shown: number) => `${shown} load(s) loaded`,
    showLoads: 'Show loads',
    emptyDemo: 'Empty demo',
    demoError: 'Demo error',
    clearError: 'Clear error',
    refreshFailed: 'Could not refresh loads.',
    container: 'Container',
    delivery: 'Delivery',
    activeHold: 'Active hold — contact dispatch',
  },
  account: {
    title: 'Account',
    roleLabel: 'Role (user_profiles)',
    emailLabel: 'Email',
    loadingProfile: 'Loading profile…',
    noProfile: 'No profile found. Sign in with a TMS user.',
    devMockActive: 'Dev mock session is also active',
    sessionLabel: 'Session',
    lastEvent: 'Last event',
    errorLabel: 'Error',
    refreshSession: 'Refresh session & profile',
    environment: 'Environment',
    projectLabel: 'Project',
  },
  loadDetail: {
    notFound: 'Load not found',
    loading: 'Loading load details…',
    route: 'Route',
    pickup: 'Pickup',
    delivery: 'Delivery',
    returnEmpty: 'Return',
    customer: 'Customer',
    customerPhone: 'Phone',
    customerAddress: 'Address',
    shipment: 'Shipment',
    loadType: 'Load type',
    routeType: 'Route type',
    ssl: 'SSL',
    mbol: 'MBOL',
    houseBol: 'House BOL',
    container: 'Container',
    containerSize: 'Size',
    containerType: 'Type',
    bolNumber: 'BOL',
    sealNumber: 'Seal',
    chassis: 'Chassis',
    timeline: 'Timeline',
    scheduledPickup: 'Scheduled pickup',
    actualPickup: 'Actual pickup',
    actualDelivery: 'Actual delivery',
    completed: 'Completed',
    flags: 'Load flags',
    hazmat: 'Hazmat',
    overweight: 'Overweight',
    bonded: 'Bonded',
    yes: 'Yes',
    no: 'No',
    holds: 'Active holds',
    holdsNote: 'Contact dispatch before changing status.',
    notes: 'Notes',
    messages: 'Messages',
    noMessages: 'No messages on this load.',
    pod: 'POD / Documents',
    podNote:
      'Photo/POD upload requires TMS API work (POST documents is staff-only today). See PP2_DOCUMENTACION.md §3.4.',
    podPlaceholder: '[ Placeholder: camera / gallery ]',
    screenTitle: 'Load details',
    emDash: '—',
  },
  driverActions: {
    title: 'Field actions',
    holdsBlock: 'ACTIVE_HOLDS: you cannot change status while holds are active.',
    transitionDenied: 'Transition not allowed for driver.',
    noActions: 'Load is in a final state or has no field actions.',
    updated: 'Updated',
  },
} as const;
