/** User-facing copy (English). */
export const strings = {
  app: {
    /** Display name on login, drawer, and device home screen (via app.json). */
    name: 'Tigerhawk Mobile',
    tagline: 'Houston Drayage',
  },
  auth: {
    signIn: 'Sign in',
    email: 'Email',
    password: 'Password',
    signInButton: 'Sign in',
    signingIn: 'Signing in…',
    signOut: 'Sign out',
    sessionActive: 'Session active',
    sessionNone: 'No session',
    sessionReady: 'Ready (no session)',
    supabaseLabel: 'Supabase',
    signInFailed: 'Could not sign in. Check your email and password.',
    invalidCredentials: 'Invalid email or password.',
    callbackSigningIn: 'Completing sign-in…',
    callbackFailed: 'Sign-in link failed or expired.',
    callbackInvalid: 'Invalid sign-in redirect.',
    magicLinkSent: 'Check your email for the sign-in link.',
    sendMagicLink: 'Email me a sign-in link',
    driverSubtitle: 'Driver app',
    devMockHint: 'Dev demo (mock only):',
    notDriverRole: 'This account is not a driver. Use a driver profile to access loads.',
  },
  network: {
    offlineTitle: 'No internet connection',
    offlineMessage:
      'You can still view cached screens. Pull to refresh or try again when you are back online.',
    offlineFetchBlocked:
      'No internet connection. Connect to load or update data.',
    offlineActionBlocked:
      'This action needs internet. Reconnect and try again.',
    offlineUploadBlocked:
      'Photo upload needs internet. Reconnect and try again.',
  },
  location: {
    sectionTitle: 'Your location',
    disclaimer:
      'Location is used only while this app is open to help dispatch see where you are on an assigned load. Tigerhawk Mobile does not track your location in the background.',
    permissionWhenInUseTitle: 'Location access',
    permissionWhenInUseMessage:
      'Tigerhawk Mobile needs your location while the app is open so you can share your position with dispatch for assigned loads.',
    permissionDeniedTitle: 'Location unavailable',
    permissionDeniedMessage:
      'Location was denied. You can enable it in device Settings, or contact dispatch by phone.',
    openSettings: 'Open Settings',
    notAvailableOnWeb: 'Location sharing is available on the mobile app only.',
    loading: 'Getting location…',
    shareLocation: 'Share location',
    shareLocationA11y: 'Share load, driver, and GPS details with dispatch',
    coordinatesLabel: 'Coordinates',
    accuracyLabel: 'Accuracy',
    lastUpdatedLabel: 'Updated',
    shareFailed: 'Could not read location. Try again outdoors with GPS enabled.',
    servicesDisabledMessage:
      'Turn on Location Services in your device settings, then try again.',
    lowPowerHint:
      'Battery saver is on — GPS may take longer or show lower accuracy. Move outdoors if needed.',
    shareDialogTitle: 'Share load location',
    shareMessageLoadLabel: 'Load',
    shareMessageStatusLabel: 'Status',
    shareMessageContainerLabel: 'Container',
    shareMessageRouteLabel: 'Route',
    shareMessageDriverLabel: 'Driver',
    shareMessageDriverPhoneLabel: 'Driver phone',
    shareMessageDriverEmailLabel: 'Driver email',
    shareMessageMapsLabel: 'Open in Maps',
    shareMessageFooter: 'Shared via Tigerhawk Mobile',
    openInMaps: 'Open in Maps',
    mapsLinkA11y: 'Open coordinates in maps app',
    tmsShareOnlyHint:
      'Share location sends load, driver, and GPS details to WhatsApp or other apps. Dispatch is not notified automatically in TMS.',
  },
  tabs: {
    loads: 'Loads',
    account: 'Account',
  },
  nav: {
    loads: 'My Loads',
    account: 'Account',
    logOut: 'Log Out',
    brandTitle: 'Tigerhawk Mobile',
    brandSubtitle: 'Houston Drayage',
  },
  loads: {
    title: 'My loads',
    subtitle: 'Your assigned drayage loads',
    fromSupabase: 'Data from Supabase (driver RLS)',
    fromMock: 'Mock data (client demo)',
    noData: 'No data',
    emptyTitle: 'No assigned loads',
    emptyMessage: 'There are no loads for this driver. Pull to refresh.',
    loading: 'Loading your loads…',
    loadingMore: 'Loading more…',
    retry: 'Try again',
    scrollForMore: 'Scroll for more loads',
    endOfList: 'All loads loaded',
    showingCount: (shown: number, total: number) =>
      `Showing ${shown} of ${total} loads`,
    showingMany: (shown: number) => `${shown} load(s) loaded`,
    showLoads: 'Show loads',
    emptyDemo: 'Empty demo',
    demoError: 'Demo error',
    clearError: 'Clear error',
    refreshFailed: 'Could not refresh loads.',
    container: 'Container',
    delivery: 'Delivery',
    activeHold: 'Active hold — contact dispatch',
  },
  account: {
    title: 'Account',
    driverRole: 'Driver',
    roleLabel: 'Role',
    emailLabel: 'Email',
    loadingProfile: 'Loading profile…',
    noProfile: 'No profile found. Sign in with a TMS user.',
    devMockActive: 'Dev mock session is also active',
    sessionLabel: 'Session',
    lastEvent: 'Last event',
    errorLabel: 'Error',
    refreshSession: 'Refresh session & profile',
    environment: 'Environment',
    projectLabel: 'Project',
  },
  loadDetail: {
    notFound: 'Load not found',
    loading: 'Loading load details…',
    route: 'Route',
    pickup: 'Pickup',
    delivery: 'Delivery',
    returnEmpty: 'Return',
    customer: 'Customer',
    customerPhone: 'Phone',
    customerAddress: 'Address',
    shipment: 'Shipment',
    loadType: 'Load type',
    routeType: 'Route type',
    ssl: 'SSL',
    mbol: 'MBOL',
    houseBol: 'House BOL',
    container: 'Container',
    containerSize: 'Size',
    containerType: 'Type',
    bolNumber: 'BOL',
    sealNumber: 'Seal',
    chassis: 'Chassis',
    timeline: 'Timeline',
    scheduledPickup: 'Scheduled pickup',
    actualPickup: 'Actual pickup',
    actualDelivery: 'Actual delivery',
    completed: 'Completed',
    flags: 'Load flags',
    hazmat: 'Hazmat',
    overweight: 'Overweight',
    bonded: 'Bonded',
    yes: 'Yes',
    no: 'No',
    holds: 'Active holds',
    holdsNote: 'Contact dispatch before changing status.',
    notes: 'Notes',
    messages: 'Messages',
    noMessages: 'No messages on this load.',
    pod: 'POD / Documents',
    documentsNote:
      'BOL, rate confirmations, and other dispatch uploads appear here. Below, you can add your own photos or images—one file per upload. Pull to refresh after any upload.',
    documentsLoading: 'Loading documents…',
    noDocuments: 'No documents on this load yet.',
    documentView: 'View',
    documentOpenFailed: 'Could not open document',
    documentLinkExpired:
      'This download link has expired. Pull down on this screen to refresh the list, then tap View again.',
    documentRemoved:
      'This file is no longer on the load. Pull down to refresh the document list.',
    documentUnavailable:
      'This file could not be opened. Pull down to refresh, or ask dispatch if the problem continues.',
    documentNoUrl:
      'This file has no download link yet. Pull to refresh or ask dispatch to re-upload.',
    documentOpening: 'Opening document…',
    driverEvidenceTitle: 'Driver photo (optional)',
    driverEvidenceHint:
      'Add photos or images of documents of interest (delivery, seal, damage, delay, or other incidents). Upload one file at a time—you can add as many as you need by uploading again. Dispatch sees each file in TMS Documents and may remove them; you cannot delete from the app.',
    driverDocBadge: 'from mobile',
    podAddPhoto: 'Add driver photo',
    podAddPhotoA11y: 'Add driver photo from camera or gallery',
    podPickTitle: 'Add photo',
    podPickMessage: 'Choose camera or photo library.',
    podPickCamera: 'Take photo',
    podPickGallery: 'Choose from gallery',
    podConfirmHint:
      'Check the photo or document image is clear, then upload or cancel. To add another file, upload again after this one succeeds.',
    podUpload: 'Upload photo',
    podUploadA11y: 'Upload driver photo to TMS',
    podCancel: 'Cancel',
    podCancelA11y: 'Cancel photo upload',
    podDiscardTitle: 'Discard photo?',
    podDiscardMessage: 'The selected photo will not be uploaded.',
    podDiscardConfirm: 'Discard',
    podKeepEditing: 'Keep photo',
    podPreviewA11y: 'Preview of selected driver photo',
    podUploadSuccess: 'Photo uploaded. It will appear in TMS Documents and in this list without reloading.',
    driverUploadInvalidMime:
      'Only JPEG, PNG, HEIC, or WebP images can be uploaded (maximum 50 MB).',
    driverUploadFileTooLarge: 'This photo exceeds the 50 MB limit. Choose a smaller file.',
    driverUploadEmptyFile: 'This file is empty. Choose another photo.',
    podOfflineHint: 'Connect to the internet to upload a driver photo.',
    screenTitle: 'Load details',
    emDash: '—',
  },
  waitTime: {
    sectionTitle: 'Delivery wait time',
    phaseIdle: 'Not started',
    phaseFree: 'Free waiting time',
    phaseBillable: 'Billable wait',
    phaseStopped: 'Stopped',
    freeRemaining: (minutes: number) =>
      `${minutes} min free time remaining`,
    exceededBanner:
      'Waiting time exceeded — dispatch has been notified. Billable time may apply.',
    mockHint: 'Demo mode — timer stored locally (Phase A).',
    startWaitTime: 'Start wait time',
    startWaitTimeHint:
      'Tap when you are present for unloading. This starts the wait timer and billing clock.',
    startWaitTimeA11y: 'Start delivery wait timer when present for unloading',
    endWaitTime: 'End wait time',
    endWaitTimeHint: 'Stops the timer only. Load status stays the same.',
    endWaitTimeA11y: 'Stop the delivery wait timer without changing load status',
    syncHint: 'Syncing wait time with the server…',
    paySummaryTitle: 'Your wait pay',
    accruedTimeLabel: 'Accrued wait time',
    estimatedPayLabel: 'Estimated wait pay',
    payEstimateHint:
      'Estimate while the timer runs. Final pay is confirmed when the load is completed.',
    payReadOnlyHint: 'Read-only. Contact dispatch with questions about your pay.',
    paySummaryA11y: 'Read-only summary of accrued wait time and estimated pay',
  },
  driverActions: {
    title: 'Field actions',
    transitionDenied: 'Transition not allowed for driver.',
    noActions: 'Load is in a final state or has no field actions.',
    updated: 'Updated',
    sessionRequired: 'Session expired. Sign in again.',
    updateFailed: 'Failed to update status.',
    changeStatusA11y: 'Change status to',
    blockedByHoldsA11y: 'Blocked while holds are active',
  },
} as const;
